### ISSUE TITLE
Link to jetpack foundation in readme is broken

### ISSUE THREAD

**Issue by bangoker** [googlesamples/android-sunflower#411]
The first link in the Libraries Used section of the readme files points to https://developer.android.com/jetpack/foundation/, which leads to a 404 page.

**Comment by nic0lette** [comment]
Thanks for pointing that out!

It looks like a few of the links in the README have fallen out of date and should be updated. (For example, there's also a link to the support library version of AppCompat, while Sunflower has migrated to AndroidX.)

**Comment by gryclmn** [comment]
May I would be happy to help with this as a first issue?
From what I can find here closest [link](https://developer.android.com/jetpack/components)?

**Comment by tiembo** [comment]
@gryclmn yes, feel free to submit a PR to update the links!

As @nic0lette mentioned, the README is indeed due for a larger refresh.

**Comment by gryclmn** [comment]
Edits and Pull Request made.

A couple side notes:
The ReadMe references "the latest version of Android Studio **3.3**" whereas the latest is 3.4.1. Should "3.3" just be dropped so it says "the latest version of Android Studio"?
The Support section links to a Google+ Community. Since Google+ is shut down this should be removed.

I would be happy to make these minor fixes as well. As this is my first PR I wasnt sure what was the best way to proceed... rename this issue to something along the lines of "Update ReadMe" or make a new issue for each of the above concerns?

Thank you for letting me help out!

**Comment by tiembo** [comment]
Thanks for the PR to update the links!

Feel free to open another one for Android Studio.  You're correct in that Sunflower will always aim to run on the latest stable version of Android Studio.
